services:
  # Node Express Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: country-trivia-backend
    restart: unless-stopped
    user: "backend:backend_group"
    env_file: .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - "5050:5050"

  # PostgreSQL Database Service
  db:
    image: postgres:17-alpine
    container_name: country-trivia-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRESQL_DB}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Vite React Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: portfolio-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5000:80"

volumes:
  postgres_data:
