services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: country-trivia-frontend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: country-trivia-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=https://db.rajivwallace.com
      - DB_PORT=5432
      - VAULT_ADDR=https://vault.rajivwallace.com
      - VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - VAULT_SECRET_ID=${VAULT_SECRET_ID}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
