# Generated by Django 5.2.7 on 2025-10-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
