# Generated by Django 5.2.7 on 2026-02-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_country_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryFunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fun_facts', to='trivia.country')),
            ],
        ),
    ]
