# Generated by Django 5.2.7 on 2026-02-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_quiztopic_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(blank=True, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_type', models.CharField(choices=[('fact_error', 'Fact is wrong'), ('typo', 'Typo or Grammar'), ('ui_bug', 'UI/Visual Bug'), ('other', 'Other')], max_length=20)),
                ('user_note', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
